### ISSUE TITLE
Adicionar Git Pages - Missão 01

### ISSUE THREAD

**Issue by MatsFidelis** [mdsreq-fga-unb/2023.2-NutriPlanner#1]
## Descrição da Issue
Conforme descrito no plano de ensino da disciplina de Requisitos de Software, a entrega da missão 01 é referente a criação do Git Pages do nosso Projeto.

## Tasks:
- [x] Levantar dados para serem alocados na página
- [x] Criação da Página

## Critérios de Aceitação:
- [x] Conter todas as informações requisitadas no plano de ensino
- [x] Restante da equipe visualizar e aprovar

## Assignees
@MatsFidelis com auxílio de @Leanddro13

**Comment by MatsFidelis** [comment]
Foi realizado a criação e deploy do GitPages, já sendo possível seu acesso !!
