### ISSUE TITLE
[REQUISITOS] Documentação de requisitos funcionais e não funcionais

### ISSUE THREAD

**Issue by MillenaQueiroz** [mdsreq-fga-unb/2023.2-NutriPlanner#3]
## Descrição da Issue
O propósito desta issue é documentar de forma abrangente todos os requisitos coletados durante a sessão de brainstorming para o projeto de software voltado para nutricionistas. A documentação precisa ser clara, organizada e de fácil compreensão para que possa servir como base para o desenvolvimento do software.

## Tasks:
- [x] Revisar a lista de requisitos coletados durante a sessão de brainstorming.
- [x] Organizar os requisitos em categorias, como requisitos funcionais e não funcionais.

## Critérios de Aceitação:
- [x] Documentação dos requisitos identificados.
- [x] Requisitos organizados de forma lógica e fácil de acessar.
- [x] Aprovação dos stakeholders relevantes quanto à precisão e compreensão dos requisitos.

**Comment by MatsFidelis** [comment]
No dia 08/10/2023 foi realizado a criação do documento em uma reunião com os membros da equipe, e no dia 12/10/2023 foi realizado a revisão e seleção dos requisitos que seriam mantidos e utilizados. 

Issue finalizada 👍🏻
