### ISSUE TITLE
[PROTÓTIPO] Fluxo de geração de dieta e treino 

### ISSUE THREAD

**Issue by MillenaQueiroz** [mdsreq-fga-unb/2023.2-NutriPlanner#4]
## Descrição da Issue
O objetivo desta issue é iniciar o processo de criação de um protótipo de baixa fidelidade para o fluxo de cadastro de dieta e treino do sistema web. O protótipo de baixa fidelidade servirá como uma representação inicial e simplificada do sistema, permitindo a visualização e validação das funcionalidades essenciais antes da elaboração de um protótipo mais detalhado.

## Tasks:
- [x] Criar esboços de telas que representem de forma simplificada as interações e fluxo do cadastro de dieta e treino.
- [x] Estabelecer o fluxo principal para o cadastro de dieta e treino, indicando a sequência de ações que o usuário deve realizar.

## Critérios de Aceitação:
- [x]  O protótipo de baixa fidelidade deve refletir as funcionalidades essenciais definidas para o cadastro de dieta e treino.
- [x]  O protótipo de baixa fidelidade deve estar pronto para a fase de refinamento e criação de um protótipo de alta fidelidade.

**Comment by MatsFidelis** [comment]
Realização do protótipo de baixa fidelidade feito com sucesso, prosseguir para a seguinte fase com criação de um protótipo com maior detalhamento !!
