### ISSUE TITLE
[DOCUMENTAÇÃO] Critérios de aceitação 

### ISSUE THREAD

**Issue by MillenaQueiroz** [mdsreq-fga-unb/2023.2-NutriPlanner#41]
## Descrição da Issue
Estamos trabalhando no desenvolvimento de novas funcionalidades para a nossa aplicação, e é fundamental garantir que todas as histórias de usuário tenham critérios de aceitação claramente definidos. Isso ajudará a garantir uma entrega consistente e apropriada das funcionalidades.

## Tasks:

- [x] Revisar as histórias de usuário atualmente no backlog.
- [x] Identificar e definir critérios de aceitação claros e mensuráveis para cada história.
- [x] Documentar os critérios de aceitação na seção apropriada de cada história de usuário.

## Critérios de Aceitação:

- [x] Todos os critérios de aceitação estão documentados para cada história de usuário.
- [x] Os critérios de aceitação são específicos, mensuráveis, alcançáveis, relevantes e temporizáveis (critérios SMART).
- [x] Os critérios de aceitação refletem as expectativas do usuário e os requisitos do negócio.

## Entrega
- [x] Os critérios de aceitação foram adicionados ao GitHub pages
