### ISSUE TITLE
[ATIVIDADE] Criação de um backlog USM

### ISSUE THREAD

**Issue by arthurgrandao** [mdsreq-fga-unb/2023.2-NutriPlanner#42]
## Descrição da Issue
Criação de um backlog, utilizando User Story Mapping, para o 'ComunEventos', que está descrito em um exercício pelo professor. 

## Tasks:
- [x] Identificação de personas
- [x] Definição de objetivos e jornadas
- [x] Criação de histórias de usuário
- [x] Priorização das histórias

## Critérios de Aceitação:
- [x] O USM foi completamente preenchido
- [x] A equipe o revisou e concluiu que está adequado

## Entrega
- [x] O USM foi adicionado ao GitHub pages

**Comment by arthurgrandao** [comment]
O USM foi devidamente revisado e adicionado ao Pages.
