### ISSUE TITLE
[ATIVIDADE] Ajustes no PBB

### ISSUE THREAD

**Issue by arthurgrandao** [mdsreq-fga-unb/2023.2-NutriPlanner#43]
## Descrição da Issue
Após ouvirmos as considerações do professor a respeito das apresentações em sala de aula dos PBBs feitos pela turma, percebemos que nosso PBB estava incorreto e que necessitava de mudanças para que pudesse ser entregue ao final da missão atual. 

## Tasks:
- [x] Revisar problemas e expectativas do produto
- [x] Revisar as atividades das personas
- [x] Desenvolver funcionalidades
- [x] Criar PBIs das funcionalidades
- [x] Derivar histórias de usuário e seus respectivos critérios de aceitação 

## Critérios de Aceitação:
- [x] As personas e suas atividades estão condizentes com o texto
- [x] A equipe revisou a atividade e concluiu que está adequada para entrega

## Entrega
- [x]  O PBB foi adicionado ao GitHub pages

**Comment by arthurgrandao** [comment]
O PBB foi devidamente revisado e adicionado ao Pages.
