### ISSUE TITLE
[ATIVIDADE] Finalização e revisão do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by MatsFidelis** [mdsreq-fga-unb/2023.2-NutriPlanner#44]
## Descrição da Issue
Transpor as ideias do protótipo de baixa fidelidade feitos no Miro, para uma ferramenta de alta fidelidade, como o Figma.

## Tasks:
- [x] Realizar a criação das telas em alta fidelidade
- [x] Verificação com o MVP
- [x] Inserir elementos de acordo com a lista de Requisitos Funcionais

## Critérios de Aceitação:
- [x] Protótipo seguindo o padrão de cores definido pelo documento de id visual
- [x] Revisão de comentários realizado
- [x] Estar alinhado com a lista de Requisitos Funcionais
- [x] Estar alinhado com a Verificação do MVP

## Entrega
- [ ] O protótipo de alta fidelidade foi adicionado ao GitHub pages
