### ISSUE TITLE
[Atividade] Ajustes no pages

### ISSUE THREAD

**Issue by Maliz30** [mdsreq-fga-unb/2023.2-NutriPlanner#45]
## Descrição da Issue
Durante o ponto de controle, foram apontados, pelo professor, alguns erros no GitHub Pages que precisam ser corrigidos antes da entrega ao fim da missão 3.

## Tasks:
- [ ] Adicionar ciclos de cada ata 
- [ ] Separar as atas por sprint
- [ ] Reorganizar os ciclos de interações
- [ ] Acrescentar o protótipo de alta fidelidade no ciclo de design

## Critérios de Aceitação:
- [ ] A equipe revisou as correções e concluiu que estão adequadas para entrega

## Entrega
- [ ]  Os ajustes foram adicionados ao GitHub pages
