### ISSUE TITLE
[PROTÓTIPO] Criação de Identidade Visual 

### ISSUE THREAD

**Issue by MillenaQueiroz** [mdsreq-fga-unb/2023.2-NutriPlanner#5]
## Descrição da Issue
Esta issue tem como objetivo iniciar o processo de criação da identidade visual para o sistema web. A identidade visual é crucial para estabelecer a aparência e o estilo do sistema, proporcionando uma experiência visualmente atraente e coesa para os usuários.

## Tasks:
- [x] Realizar pesquisa de referências de identidade visual para sistemas web similares e de mercado.
- [x] Definir os elementos visuais chave, incluindo cores, tipografia, ícones e imagens que representarão a identidade visual do sistema.
- [x] Criar o logotipo e ícone que representarão o sistema, levando em consideração os elementos visuais definidos anteriormente.

## Critérios de Aceitação:
- [x] A identidade visual deve refletir a essência do sistema.
- [x] Todos os elementos visuais devem estar em conformidade com as diretrizes definidas.
- [x] A identidade visual deve estar pronta para ser aplicada em todas as telas e componentes do sistema.

**Comment by MillenaQueiroz** [comment]
Done. [Link](https://www.figma.com/file/HqFtU4inGyyvfgxasRWzIB/Guardioes-do-bem-e-do-leite?type=design&node-id=26-22&mode=design&t=YQo7TC84YIbTJe66-4).
