### ISSUE TITLE
[US25] Eu, como nutricionista, quero ser capaz de cadastrar pacientes, inserindo nome, e-mail, telefone, endereço, altura, peso e medidas corporais para armazenar as informações no sistema.

### ISSUE THREAD

**Issue by arthurgrandao** [mdsreq-fga-unb/2023.2-NutriPlanner#57]
## Descrição da Issue
Nesta issue estaremos desenvolvendo a história de usuário de número 25 do nosso backlog.

US25 - Eu, como nutricionista, quero ser capaz de cadastrar pacientes, inserindo nome, e-mail, telefone, endereço, altura, peso e medidas corporais para armazenar as informações no sistema.

## Tasks:
- [ ] O sistema deve ser capaz de cadastrar pacientes, inserindo nome, e-mail, telefone, endereço, altura, peso e medidas corporais para armazenar as informações no sistema

## Critérios de Aceitação:
- [ ] Os campos nome, e-mail, telefone, endereço, altura, peso e medidas corporais devem ser obrigatórios.
- [ ] O sistema deve realizar validação para garantir que apenas emails válidos sejam aceitos.
- [ ] O sistema deve realizar validação para garantir que apenas telefones válidos sejam aceitos.

## Telas
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/85596312/c3fcea54-f43e-4b83-a135-f29223a19849)

## DoR - Definition of Ready
A US só poderá ser desenvolvida se atender aos requisitos abaixo:

- [x] O Requisito possui está declarado de forma não ambígua?
- [x] O Requisito pode ser realizado dada a realidade do projeto (restrições de tempo e técnicas)?
- [x] O Requisito possui informação necessária para ser trabalhado? 
- [x] O Requisito possui critérios de aceitação?
- [x] O protótipo foi validado pelo cliente?
- [x] O requisito segue os critérios de priorização?
