### ISSUE TITLE
[US16] - Eu, como nutricionista, quero ser capaz de criar treinamentos para meus pacientes usando o sistema, para facilitar a realização dessa atividade.

### ISSUE THREAD

**Issue by MillenaQueiroz** [mdsreq-fga-unb/2023.2-NutriPlanner#65]
## Descrição da Issue
Eu, como nutricionista, quero ser capaz de criar treinamentos para meus pacientes usando o sistema, para facilitar a realização dessa atividade.

## Tasks:
- [ ] Fazer interface
- [ ] Fazer backend

## Critérios de Aceitação:
- [ ] 1. O sistema deve permitir que o usuário monte até 7 listas de exercícios, contendo região focal, o dia da semana em que a lista deve ser executada, a duração dos exercícios aeróbicos do dia, o intervalo de tempo entre séries e exercícios, a sequência de exercícios, suas respectivas quantidades e técnicas avançadas.
- [ ] 2. O sistema deve permitir que o usuário preencha através de inputs que aceitem no máximo 100 caracteres, a região focal, o dia da semana em que a lista deve ser executada, a duração dos exercícios aeróbicos do dia e o intervalo de tempo entre séries e exercícios.
- [ ] 3. Os exercícios que deverão compor as listas de exercícios devem ser escolhidos a partir de um conjunto de exercícios pré-cadastrados pelo usuário, no sistema.
- [ ] 4. O sistema deve permitir que o usuário preencha, através de inputs, a quantidade de séries de cada exercício.
- [ ] 5. O sistema deve permitir que o usuário preencha, através de inputs, a técnica avançada de cada exercício.

**Comment by MillenaQueiroz** [comment]
Conforme alinhado com o cliente, o critério de aceitação "Os exercícios que deverão compor as listas de exercícios devem ser escolhidos a partir de um conjunto de exercícios pré-cadastrados pelo usuário, no sistema" não faz sentido ser algo pré-cadastrado pois o cliente precisaria, a cada vez que houver um exercício novo, ir na interface de cadastro de exercícios e adicionar e depois puxar na de cadastro de treino. O que o cliente quer é ter uma interface em que possa digitar o nome do exercício com maior liberdade e agilidade.
