### ISSUE TITLE
[US17] Eu, como nutricionista, devo ser capaz de visualizar treinamentos armazenados na plataforma para rever os treinamentos feitos para meus pacientes.

### ISSUE THREAD

**Issue by arthurgrandao** [mdsreq-fga-unb/2023.2-NutriPlanner#67]
## Descrição da Issue
[Descrever de forma sucinta a issue, colocando quaisquer informações necessárias para a realização da mesma.]

US17 - Eu, como nutricionista, devo ser capaz de visualizar treinamentos armazenados na plataforma para rever os treinamentos feitos para meus pacientes.

## Tasks:
- [ ] Eu, como nutricionista, devo ser capaz de visualizar treinamentos armazenados na plataforma para rever os treinamentos feitos para meus pacientes.

## Telas
A ser feito

## Critérios de Aceitação:
- [ ] O sistema deve permitir que o nutricionista visualize as listas de exercícios cadastradas, contendo região focal, dia da semana em que a lista deve ser executada, a duração dos exercícios aeróbicos do dia, o intervalo entre séries e exercícios, a sequência de exercícios, suas respectivas quantidades e técnicas avançadas

## DoR - Definition of Ready
A US só poderá ser desenvolvida se atender aos requisitos abaixo:

- [ ] O Requisito possui está declarado de forma não ambígua?
- [ ] O Requisito pode ser realizado dada a realidade do projeto (restrições de tempo e técnicas)?
- [ ] O Requisito possui informação necessária para ser trabalhado? 
- [ ] O Requisito possui critérios de aceitação?
- [ ] O protótipo foi validado pelo cliente?
- [ ] O requisito segue os critérios de priorização?

**Comment by MillenaQueiroz** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/60625345/b7e595c3-460d-4e45-915f-f13cb0ff4209)
