### ISSUE TITLE
[US09] - Eu, como nutricionista, devo ser capaz de buscar pacientes cadastrados por nome, a fim de agilizar o atendimento.

### ISSUE THREAD

**Issue by arthurgrandao** [mdsreq-fga-unb/2023.2-NutriPlanner#82]
## Descrição da Issue
Funcionalidade de pesquisa de pacientes.

## Tasks:
- [x] Buscar no banco de dados por pacientes pelo nome

## Protótipo
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/85596312/54bac437-f226-4183-a25b-367f46a16b0a)

## Critérios de Aceitação:
- [x] O input de busca deve aceitar no máximo 150 caracteres.
- [x] A busca deve ser insensível a maiúsculas e minúsculas, encontrando os pacientes independentemente da formatação.
- [x] A lista de resultados da busca deve exibir os pacientes com nome, idade, data de nascimento e status de atividade.

### DoR - Definition of Ready 

A US só poderá ser desenvolvida se atender aos requisitos abaixo:

- [x] O Requisito possui está declarado de forma não ambígua?
- [x] O Requisito pode ser realizado dada a realidade do projeto (restrições de tempo e técnicas)?
- [ ] O Requisito possui informação necessária para ser trabalhado? 
- [ ] O Requisito possui critérios de aceitação?
- [x] O protótipo foi validado pelo cliente?
- [x] O requisito segue os critérios de priorização?

**Comment by LucasSpinosa** [comment]
Quando o componente estiver pronto, colocar ele na Home.
